---
pdf_document: default
author: 'NM2207: Computational Media Literacy'
date: "`r Sys.Date()`"
output:
  pdf_document: default
title: "Week-7: Code-along"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Data: Palmer Penguins

```{r, eval=T,echo=TRUE}
# Enter code here
library(tidyverse)
library(palmerpenguins)
glimpse(penguins)
```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins)

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm))

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm)) +
  geom_point()

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point()

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length")

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins")

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)",
       y = "Bill length (mm)")

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)",
       y = "Bill length (mm)",
       colour = "Species")

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)",
       y = "Bill length (mm)",
       colour = "Species",
       caption = "Source: Palmer Station LTER/palmerpenguins package")

```
<br>
```{r, eval=T,echo=TRUE}
# Enter code here
ggplot(data = penguins,
       mapping = aes(x = bill_depth_mm,
                     y = bill_length_mm,
                     colour = species)) +
  geom_point() +
  labs(title = "Bill depth and length",
       subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Bill depth (mm)",
       y = "Bill length (mm)",
       colour = "Species",
       caption = "Source: Palmer Station LTER/palmerpenguins package") +
  scale_colour_viridis_d()

```
<br>
```{r, eval=T,echo=TRUE}
# Alternative
ggplot(penguins) + # Data layer
  aes(x = bill_depth_mm,
      y = bill_length_mm,
      colour = species) + # Aesthetics layer
  geom_point() + # Geometric layer
  scale_colour_viridis_d()

```
<br>
```{r, eval=T,echo=TRUE}
#Shape
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm, 
           colour = species,
           shape = island)) +
  geom_point() + 
  scale_colour_viridis_d()
```
<br>
```{r, eval=T,echo=TRUE}
#Shape
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm, 
           colour = species,
           shape = species)) +
  geom_point() + 
  scale_colour_viridis_d()
```
<br>
```{r, eval=T,echo=TRUE}
#Size
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm, 
           colour = species,
           shape = species,
           size = body_mass_g)) +
  geom_point() + 
  scale_colour_viridis_d()
```
<br>
```{r, eval=T,echo=TRUE}
#Alpha
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm, 
           colour = species,
           shape = species,
           size = body_mass_g,
           alpha = flipper_length_mm)) +
  geom_point() + 
  scale_colour_viridis_d()
```
<br>
```{r, eval=T,echo=TRUE}
#Mapping
ggplot(penguins) +
  aes(x = bill_depth_mm,
      y = bill_length_mm,
      size = body_mass_g,
      alpha = flipper_length_mm) +
  geom_point()
```
<br>
```{r, eval=T,echo=TRUE}
#Setting
ggplot(penguins) + 
  aes(x = bill_depth_mm,
      y = bill_length_mm) +
  geom_point(size = 2, alpha = 0.5)
```
<br>
```{r, eval=T,echo=TRUE}
#Faceting
ggplot(penguins) +
  aes(x = bill_depth_mm,
      y = bill_length_mm) +
  geom_point() +
  facet_grid(species ~ island)
```
<br>
```{r, eval=T,echo=TRUE}
#Facet 2
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm)) + 
  geom_point() +
  facet_grid(species ~ sex)
```
<br>
```{r, eval=T,echo=TRUE}
#Facet 3
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm)) + 
  geom_point() +
  facet_grid(sex ~ species)
```
<br>
```{r, eval=T,echo=TRUE}
#Facet 4
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm)) + 
  geom_point() +
  facet_wrap(~ species)
```
<br>
```{r, eval=T,echo=TRUE}
#Facet 5
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm)) + 
  geom_point() +
  facet_wrap(~ species, ncol = 2)
```
<br>
```{r, eval=T,echo=TRUE}
#Facet 6
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm)) + 
  geom_point() +
  facet_grid(.~ species)
```
<br>
```{r, eval=T,echo=TRUE}
#Facet and color
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm,
           color = species)) + 
  geom_point() +
  facet_grid(species ~ sex) +
  scale_color_viridis_d()
```
<br>
```{r, eval=T,echo=TRUE}
#Facet and color
ggplot(penguins, 
       aes(x = bill_depth_mm, 
           y = bill_length_mm,
           color = species)) + 
  geom_point() +
  facet_grid(species ~ sex) +
  scale_color_viridis_d() +
  guides(color = "none")
```
<br>
```{r, eval=T,echo=TRUE}
#Visualizing numeric variables
library(openintro)
glimpse(loans_full_schema)
```
<br>
```{r, eval=T,echo=TRUE}
#Selected Variables
loans <- loans_full_schema %>%
  select(loan_amount, interest_rate, term, grade, state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```
<br>
```{r, eval=T,echo=TRUE}
#Histogram
ggplot(loans) + 
  aes(x = loan_amount) +
  geom_histogram()
```
<br>
```{r, eval=T,echo=TRUE}
#Histogram and binwidth = 1000
ggplot(loans) + 
  aes(x = loan_amount) +
  geom_histogram(binwidth = 1000)
```
<br>
```{r, eval=T,echo=TRUE}
#Histogram and binwidth = 5000
ggplot(loans) + 
  aes(x = loan_amount) +
  geom_histogram(binwidth = 5000)
```
<br>
```{r, eval=T,echo=TRUE}
#Histogram and binwidth = 20000
ggplot(loans) + 
  aes(x = loan_amount) +
  geom_histogram(binwidth = 20000)
```
<br>
```{r, eval=T,echo=TRUE}
#Customizing histograms
ggplot(loans, 
       aes(x = loan_amount)) + 
  geom_histogram(binwidth = 5000) +
  labs(x = "Loan amount ($)", 
       y = "Frequency", 
       title = "Amounts of Lending Club loans")

```
<br>
```{r, eval=T,echo=TRUE}
#Fill with a categorical variable
ggplot(loans, 
       aes(x = loan_amount, 
           fill = homeownership)) +
  geom_histogram(binwidth = 5000, alpha = 0.5 ) +
  labs(x = "Loan amount ($)",
       y = "Frequency",
       title = "Amounts of Lending Club loans")
```
<br>
```{r, eval=T,echo=TRUE}
#Facet with a categorical variable
ggplot(loans, 
       aes(x = loan_amount, 
           fill = homeownership)) + 
  geom_histogram(binwidth = 5000) +
  labs(x = "Loan amount ($)",
       y = "Frequency",
       title = "Amounts of Lending Club loans") +
  facet_wrap(~ homeownership, nrow = 3)
```
<br>
```{r, eval=T,echo=TRUE}
#Density plot
ggplot(loans, 
       aes(x = loan_amount)) +
  geom_density()
```
<br>
```{r, eval=T,echo=TRUE}
#Density plots and adjusting bandwidth
ggplot(loans, 
       aes(x = loan_amount)) +
  geom_density(adjust = 0.5)
```
<br>
```{r, eval=T,echo=TRUE}
#Density plots and adjusting bandwidth
ggplot(loans, 
       aes(x = loan_amount)) +
  geom_density(adjust = 1) #default
```
<br>
```{r, eval=T,echo=TRUE}
#Density plots and adjusting bandwidth
ggplot(loans, 
       aes(x = loan_amount)) +
  geom_density(adjust = 2)
```
<br>
```{r, eval=T,echo=TRUE}
#Customizing density plots
ggplot(loans, 
       aes(x = loan_amount)) +
  geom_density(adjust = 2) +
  labs( x = "Loan amount ($)",
        y = "Density",
        title = "Amounts of Lending Club loans")
```
<br>
```{r, eval=T,echo=TRUE}
#Adding a categorical variable
ggplot(loans, 
       aes(x = loan_amount,
           fill = homeownership)) +
  geom_density(adjust = 2, alpha = 0.5) +
  labs( x = "Loan amount ($)",
        y = "Density",
        title = "Amounts of Lending Club loans",
        fill = "Homeownership")
```
<br>
```{r, eval=T,echo=TRUE}
#Box plot
ggplot(loans, 
       aes(x = interest_rate)) +
  geom_boxplot()
```
<br>
```{r, eval=T,echo=TRUE}
#Box plot and outliers
ggplot(loans, 
       aes(x = annual_income)) +
  geom_boxplot()
```
<br>
```{r, eval=T,echo=TRUE}
#Customizing box plots
ggplot(loans, 
       aes(x = interest_rate)) +
  geom_boxplot() +
  labs(x = "Interest rate (%)",
       y = NULL,
       title = "Interest rates of Lending Club loans") +
  theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )
```
<br>
```{r, eval=T,echo=TRUE}
#Adding a categoric variable
ggplot(loans, 
       aes(x = interest_rate,
           y = grade)) +
  geom_boxplot() +
  labs(x = "Interest rate (%)",
       y = "Grade",
       title = "Interest rates of Lending Club loans",
       subtitle = "by grade of loan")
```
<br>
```{r, eval=T,echo=TRUE}
#Scatterplot
ggplot(loans, 
       aes(x = debt_to_income, 
           y = interest_rate)) +
  geom_point()
```
<br>
```{r, eval=T,echo=TRUE}
#Hex plot
ggplot(loans, 
       aes(x = debt_to_income, 
           y = interest_rate)) +
  geom_hex()
```
<br>
```{r, eval=T,echo=TRUE}
#Hex plot
ggplot(loans %>% filter(debt_to_income < 100),
       aes(x = debt_to_income, 
           y = interest_rate)) +
  geom_hex()
```
<br>
```{r, eval=T,echo=TRUE}
#Bar plot
ggplot(loans, 
       aes(x = homeownership)) +
  geom_bar()
```
<br>
```{r, eval=T,echo=TRUE}
#Segmented bar plot
ggplot(loans, 
       aes(x = homeownership,
           fill = grade)) +
  geom_bar()
```
<br>
```{r, eval=T,echo=TRUE}
#Segmented bar plot
ggplot(loans, 
       aes(x = homeownership,
           fill = grade)) +
  geom_bar(position = "fill")
```
<br>
```{r, eval=T,echo=TRUE}
#Customizing bar plots
ggplot(loans, 
       aes(y = homeownership, 
           fill = grade)) + 
  geom_bar(position = "fill") +
  labs( x = "Proportion",
        y = "Homeownership",
        fill = "Grade",
        title = "Grades of Lending Club loans")
```
<br>
```{r, eval=T,echo=TRUE}
#Violin plots
ggplot(loans, 
       aes(x = homeownership, 
           y = loan_amount)) +
geom_violin()
```
<br>
```{r, eval=T,echo=TRUE}
#Ridge plots
library(ggridges)
ggplot(loans, 
       aes(x = loan_amount,
           y = grade, 
           fill = grade, 
           color = grade)) +
  geom_density_ridges(alpha = 0.5)
```
<br>

